### PR TITLE
the superior licence

### PR DESCRIPTION
**Pull request by wafflecoffee**

### CODE REVIEW

**Comment by HiItsDevin** [comment]
this is actually REALLY cursed and i hate it

**Comment by Deviouslrd** [comment]
what, you dont want your mod to be ARR?

I dont see any issue with it ¯\_(ツ)_/¯

**Comment by HiItsDevin** [comment]
> what, you dont want your mod to be ARR?
> 
> I dont see any issue with it ¯_(ツ)_/¯

you lost your fucking arm
image

**Comment by wafflecoffee** [comment]
https://tenor.com/view/disney-moana-youre-welcome-maui-dance-gif-15810606

**Comment by Deviouslrd** [comment]
> > what, you dont want your mod to be ARR?
> > I dont see any issue with it ¯_(ツ)_/¯
> 
> you lost your fucking arm
> image

how the fuck does this happen

**Comment by Deviouslrd** [comment]
Right.
Backslashes.

**Pull request closed without merging**
